# Use the existing image as the base
FROM dyrnq/open-webui

# Update pip and install necessary Python libraries
RUN pip install --upgrade pip && \
    pip install pandas_datareader

# Replace <your-python-library> with the actual libraries you want to install
