version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1,2,3
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    runtime: nvidia
    networks:
      - app-network

  open_web_ui:
    image: ghcr.io/open-webui/open-webui:main
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    runtime: nvidia
    networks:
      - app-network

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - pipelines:/app/pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    runtime: nvidia
    networks:
      - app-network

volumes:
  ollama:
  open-webui:
  pipelines:

networks:
  app-network:
    driver: bridge
