version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    runtime: nvidia
    networks:
      - app-network

  open_web_ui:
    image: dyrnq/open-webui
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    runtime: nvidia
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    network_mode: "host"
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
    restart: always

  pipelines:
    build:
      context: ./pipelines
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PIPELINES_URLS="https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py"
    volumes:
      - pipelines:/app/pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    runtime: nvidia
    networks:
      - app-network

networks:
  app-network:

volumes:
  ollama:
  open-webui:
  pipelines:
